# This is how you tell travis to run the build on the new container (docker) based infrastructure
sudo: false

language: node_js
node_js:
  - "0.10.40"

# Since sudo isn't possible anymore (for now), meteor can't add a link to itself to /usr/local/bin,
# so you'll have to add the meteor installation directory to the PATH yourself.
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - meteor --version
  - "npm install -g spacejam"

script:
  - "npm run testall"
  - "spacejam test-packages --use-system-phantomjs --driver-package=practicalmeteor:mocha-console-runner"