# This is how you tell travis to run the build on the new container (docker) based infrastructure
sudo: false

language: node_js
node_js:
  - "0.10.45"

cache:
  directories:
    - node_modules

# Since sudo isn't possible anymore (for now), meteor can't add a link to itself to /usr/local/bin,
# so you'll have to add the meteor installation directory to the PATH yourself.
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - meteor --version
  - "npm install -g spacejam@1.6.1 coffee-script"
  - "meteor add practicalmeteor:mocha-console-runner"
  - "meteor remove kadira:debug"
  - "npm install -g eslint@2.13.1 eslint-config-standard@5.3.1 eslint-config-standard-jsx@1.2.1 eslint-plugin-standard@1.3.2 eslint-plugin-promise@1.3.2 eslint-plugin-react@5.2.2"

# TODO activate test-packages again when needed
# "meteor reset"
# "npm run test-packages"
script:
  - "npm run test-travis"
  - "meteor reset"
  - "npm run testall-travis"
  - "npm run lint"