# This is how you tell travis to run the build on the new container (docker) based infrastructure
sudo: false

language: node_js
node_js:
  - "4.4.7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules

# Since sudo isn't possible anymore (for now), meteor can't add a link to itself to /usr/local/bin,
# so you'll have to add the meteor installation directory to the PATH yourself.
before_install:
#  - "curl https://install.meteor.com | /bin/sh"
#  - export PATH="$HOME/.meteor:$PATH"
#  - meteor --version
#  - "npm install -g spacejam@1.6.1 coffee-script"
#  - "meteor add practicalmeteor:mocha-console-runner"
#  - "meteor remove appcache"
  - "npm install -g eslint@3.11.1 eslint-config-standard@6.2.1 eslint-config-standard-jsx@3.2.0 eslint-plugin-standard@2.0.1 eslint-plugin-promise@3.4.0 eslint-plugin-react@6.8.0"

# - "meteor reset"
# - "npm run test-packages"
# - "npm run test-travis"
# - "meteor reset"
script:
#  - "npm run testall-travis" removed for now till the project structure has changed
  - "npm run lint"
