# This is how you tell travis to run the build on the new container (docker) based infrastructure
sudo: false

language: node_js
node_js:
  - "0.10.45"

cache:
  directories:
    - node_modules

# Since sudo isn't possible anymore (for now), meteor can't add a link to itself to /usr/local/bin,
# so you'll have to add the meteor installation directory to the PATH yourself.
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - meteor --version
  - "npm install -g spacejam coffee-script"
  - "meteor add practicalmeteor:mocha-console-runner"
  - "meteor remove kadira:debug"
  - "npm install -g eslint eslint-config-standard eslint-config-standard-jsx eslint-plugin-standard eslint-plugin-promise eslint-plugin-react"

script:
  - "npm run test-travis"
  - "meteor reset"
  - "npm run testall-travis"
  - "meteor reset"
  - "npm run test-packages"
  - "npm run lint"